---
updates:
  # Enable version updates for Cypress
  - directory: "/ECBackend/Cypress"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  # Enable version updates for WebUI
  - directory: "/ECBackend/WebUI"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"

  # Enable version updates for API
  - directory: "/ECBackend/API"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"

  # Enable version updates for Pulumi
  - directory: "/Deploy/Pulumi"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"

version: 2
