FROM hadolint/hadolint:v1.17.3-debian
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update \
 && apt-get install --no-install-recommends -y \
	python3-pip=9.0.* \
	python3-setuptools=33.1.* \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN pip3 install --quiet yamllint==1.19.0

WORKDIR /app

Copy . . 

# Sort used to make output discrete and eaiser to debug
RUN find . -name "*Dockerfile*" -print0 | sort -z | xargs -0 --max-lines=1 hadolint
RUN yamllint --strict .