version: '3.5'

services:
  packer:
    build:
      context: .
    networks:
      - ec-deploy-network
    env_file:
      - .env
      - info.env
    environment:
      - ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3

networks:
  ec-deploy-network: