FROM hashicorp/packer:1.4.5 as builder

# Prevents pip from complaining about being out of date
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 

RUN echo hello
RUN apk update && apk add --no-cache ansible=2.7.14-r0 && rm -rf /tmp/* && rm -rf /var/cache/apk/*
RUN pip3 install ansible-lint==4.1.0

COPY .ansible-lint . 
COPY build.json .
COPY playbook.yaml .

RUN packer validate build.json
RUN ansible-lint playbook.yaml