---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: symlink /usr/bin/python -> /usr/bin/python3
    raw: |
         if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
           ln --symbolic /usr/bin/python3 /usr/bin/python;
         fi
    become: true

  - name: Install required system packages for Docker
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop:
       - 'apt-transport-https=1.6.6ubuntu0.1'
       - 'ca-certificates=20180409'
       - 'curl=7.58.0-2ubuntu3.8'
       - 'software-properties-common=0.96.24.32.11'
       - 'python3-pip=9.0.1-2.3~ubuntu1.18.04.1'
       - 'virtualenv=15.1.0+ds-1.1'
       - 'python3-setuptools=39.0.1-2'

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable

  - name: Update apt and install docker-ce
    apt:
      update_cache: yes
      name: docker-ce=5:19.03.5~3-0~ubuntu-bionic

  - name: Install Docker Module for Python
    pip:
      name: docker==4.1.0

  - name: Add 'fish' repository
    apt_repository:
      repo: ppa:fish-shell/release-3

  - name: Install the package 'fish'
    apt:
      name: fish=3.0.2-1~bionic

  - name: Add the user 'ec-debug' as part of the 'docker' group
    user:
      name: ec-debug
      comment: Default user for debugging in production.
      group: docker
      shell: /usr/bin/fish
      password_lock: yes

  - name: Set authorized key
    authorized_key:
      user: ec-debug
      state: present
      key: "{{ lookup('file', './id_rsa.pub') }}"
