---
services:
  bu:
    environment:
      aws_deploy_target: production

version: '3.5'

volumes:
  ec-db-volume:
    driver: rexray/ebs:0.11.4
    driver_opts:
      size: 70
    name: ec-production-db-volume
  ec-os-volume:
    driver: rexray/ebs:0.11.4
    driver_opts:
      size: 10
    name: ec-production-os-volume
  ec-rp-volume:
    driver: rexray/ebs:0.11.4
    driver_opts:
      size: 1
    name: ec-production-rp-volume
