---
services:
  cron:
    deploy:
      restart_policy:
        condition: any
    environment:
      - "TZ=UTC"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    image: crazymax/swarm-cronjob:1.7.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  garbage_collector:
    command: ["docker", "system", "prune", "--force", "--volumes"]
    deploy:
      labels:
        - "swarm.cronjob.enable=true"
        # Every day at 3AM PST
        # Or 11AM UTC
        - "swarm.cronjob.schedule=0 11 * * *"
        - "swarm.cronjob.skip-running=true"
      mode: global
      restart_policy:
        condition: none
    image: docker:19.03.5
    volumes:
      # May not work on windows
      - /var/run/docker.sock:/var/run/docker.sock

version: '3.5'
