---
services:
  registry:
    deploy:
      restart_policy:
        condition: any
    healthcheck:
      interval: 1m30s
      retries: 3
      test: ["CMD-SHELL", "wget --quiet --tries=1 -O /dev/null http://localhost:5000/v2/ || exit 1"]
      timeout: 10s
    image: registry:2.7.1
    ports:
      - 5000:5000
    volumes:
      - prod-registry-volume:/var/lib/registry

version: '3.5'

volumes:
  prod-registry-volume: {}
