---
version: '3.5'

services:
  ssh_setup:
    build:
      context: ./SshClient
    command: ["ssh-keygen", "-b", "2048", "-q", "-t", "rsa", "-N", "", "-f", "./id_rsa"]
    volumes:
      - ./.secrets/:/keys/
    networks:
      - ec-setup-network

  packer:
    build:
      context: ./Packer
    volumes:
      - ./.secrets/id_rsa.pub:/deploy/id_rsa.pub
      - ../Server:/deploy/Server
    networks:
      - ec-deploy-network
    env_file:
      - .env
      - info.env

  ssh_connect:
    build:
      context: ./SshClient
    command: ["sh", "-c", "ssh -o StrictHostKeyChecking=no -i id_rsa -l ec-debug $$aws_host_ssh_address"]
    volumes:
      - ./.secrets/id_rsa:/keys/id_rsa
    networks:
      - ec-connect-network
    env_file:
      - info.env

  pulumi_up:
    build:
      context: ./Pulumi
    networks:
      - ec-pulumi-network
    env_file:
      - .env
      - info.env

  pulumi_destroy:
    build:
      context: ./Pulumi
    command: ["sh", "-c", "pulumi login && pulumi destroy"]
    volumes:
      - ./credentials:/root/.aws/credentials
    networks:
      - ec-pulumi-network
    env_file:
      - .env
      - info.env

networks:
  ec-deploy-network: {}
  ec-setup-network: {}
  ec-connect-network: {}
  ec-pulumi-network: {}
