---
networks:
  ec-deploy-network: {}

services:
  packer:
    build:
      context: ./Packer
    env_file:
      - .env
      - .deploy.env
    networks:
      - ec-deploy-network
    volumes:
      - ./.secrets/id_rsa.pub:/deploy/id_rsa.pub
      - ../Server:/deploy/Server

  pulumi:
    build:
      context: ./Pulumi
    env_file:
      - .env
      - .deploy.env
    networks:
      - ec-deploy-network

  ssh_connect:
    build:
      context: ./SshClient
    command: ["sh", "-c", "ssh -o StrictHostKeyChecking=no -i id_rsa -l ec-debug $$aws_host_ssh_address"]
    env_file:
      - .deploy.env
    networks:
      - ec-deploy-network
    volumes:
      - ./.secrets/id_rsa:/keys/id_rsa

  ssh_setup:
    build:
      context: ./SshClient
    command: ["ssh-keygen", "-b", "2048", "-q", "-t", "rsa", "-N", "", "-f", "./id_rsa"]
    networks:
      - ec-deploy-network
    volumes:
      - ./.secrets/:/keys/

version: '3.5'
