---
version: '3.5'

services:
  packer:
    build:
      context: ./Packer
    volumes:
      - ./.secrets/id_rsa.pub:/deploy/id_rsa.pub
      - ../Server:/deploy/Server
    networks:
      - ec-deploy-network
    env_file:
      - .env
      - .deploy.env

  pulumi:
    build:
      context: ./Pulumi
    networks:
      - ec-deploy-network
    env_file:
      - .env
      - .deploy.env

  ssh_connect:
    build:
      context: ./SshClient
    command: ["sh", "-c", "ssh -o StrictHostKeyChecking=no -i id_rsa -l ec-debug $$aws_host_ssh_address"]
    volumes:
      - ./.secrets/id_rsa:/keys/id_rsa
    networks:
      - ec-deploy-network
    env_file:
      - .deploy.env

  ssh_setup:
    build:
      context: ./SshClient
    command: ["ssh-keygen", "-b", "2048", "-q", "-t", "rsa", "-N", "", "-f", "./id_rsa"]
    volumes:
      - ./.secrets/:/keys/
    networks:
      - ec-deploy-network

networks:
  ec-deploy-network: {}
