version: '3.5'

services:
  ssh_setup:
    build:
      context: ./SshSetup
    volumes:
      - ./.secrets/:/keys/
    networks:
      - ec-setup-network

  packer:
    build:
      context: ./Packer
    volumes:
    - ./.secrets/id_rsa.pub:/deploy/id_rsa.pub
    - ../Server:/deploy/Server
    networks:
      - ec-deploy-network
    env_file:
      - .env
      - info.env

  ssh_connect:
    build:
      context: ./SshConnect
    volumes:
    - ./.secrets/id_rsa:/keys/id_rsa
    networks:
    - ec-connect-network
    env_file:
      - info.env
  

networks:
  ec-deploy-network:
  ec-setup-network:
  ec-connect-network: