---
version: '3.5'

services:
  api:
    environment:
      - unsafe_do_no_validate_user=true  # IMPORTANT: this should never be set in production

  web:
    volumes:
      - ./WebUI/:/app/
      - /app/node_modules
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  rp:
    ports:
      - "8090:2015"
    volumes:
      - ./Caddy/Caddyfile:/etc/Caddyfile

  exporter:
    build:
      context: ./Exporter
    command: ["sh", "-c", "/wait && dotnet Exporter.dll"]
    depends_on:
      - db
    environment:
      - WAIT_HOSTS=db:27017
    networks:
      - ec-network

  new_password:
    build:
      context: ./API
    command: ["dotnet", "API.dll", "--passwordGenerate"]
    networks:
      - ec-network

  redoc:
    image: redocly/redoc:v2.0.0-rc.20
    hostname: redoc
    ports:
      - "4322:80"
    depends_on:
      - rp
    environment:
      - SPEC_URL=http://localhost:8090/api/v1/openapi
    networks:
      - ec-network

volumes:
  ec-db-volume: {}
  ec-os-volume: {}
