#- Name: Jonathan Hirokazu Burns
#- ID: 2288851
#- email: jburns@chapman.edu
#- Course: 353-01
#- Assignment: Submission #2
#- Purpose: Builds, defines and starts the backend

version: '3.7'
services:
  api:
    build: 
      context: ./API
    command: sh -c "/wait && dotnet API.dll"
    ports:
    - "4321:80"
    depends_on:
    - db
    environment:
      WAIT_HOSTS: db:27017
    networks:
     - ec-network
    healthcheck:
       test: wget --quiet --tries=1 -O /dev/null http://localhost/health/ || exit 1
       interval: 1m30s
       timeout: 10s
       retries: 3

  db:
    image: mongo:3.6.14
    hostname: db
    ports:
    - "27017:27017"
    volumes:
    - ec-data-volume:/data/db
    networks:
    - ec-network
    healthcheck:
       test: mongo --quiet --eval "db.adminCommand('ping')"
       interval: 1m30s
       timeout: 10s
       retries: 3

  exporter:
    build: 
      context: ./Exporter
    command: sh -c "/wait && dotnet Exporter.dll"
    depends_on:
      - db
    volumes:
      - ./data/:/app/data
    environment:
      - WAIT_HOSTS=db:27017
    networks:
      - ec-network

  web:
    build:
      context: ./WebUI
    ports:
    - "3003:3000"
    volumes:
      - ./WebUI/:/app/
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

volumes:
  ec-data-volume:

networks:
  ec-network:
