version: '3.5'

services:
  registry:
    image: registry:2.7.1
    deploy:
      restart_policy:
        condition: any
    ports:
      - 5000:5000
    volumes:
      - infra-registry-volume:/var/lib/registry

volumes:
  infra-registry-volume: {}