#- Name: Jonathan Hirokazu Burns
#- ID: 2288851
#- email: jburns@chapman.edu
#- Course: 353-01
#- Assignment: Submission #2
#- Purpose: Builds, defines and starts the backend

version: '3.7'
services:
  web:
    volumes:
      - ./WebUI/:/app/
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
    - "3003:3000"