#- Name: Jonathan Hirokazu Burns
#- ID: 2288851
#- email: jburns@chapman.edu
#- Course: 353-01
#- Assignment: Submission #2
#- Purpose: Builds, defines and starts the backend

version: '3.7'
services:
  api:
    image: jhburns/ec-receiver-cache
    restart: always

  exporter:
    image: jhburns/ec-exporter-cache
    restart: always

  web:
    build:
      context: ./WebUI
      dockerfile: Dockerfile.production
    command: "caddy"
    image: jhburns/ec-webpage-cache
    restart: always
    ports:
    - "2015:2015"
    healthcheck:
      test: wget --quiet --tries=1 -O /dev/null http://localhost:2015/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3