version: '3'
services:
  receiver:
    build: ./Receiver
    ports:
    - "4321:80"
    volumes:
      - ./data:/app/data

  processor:
    build: ./Processor
    volumes:
      - ./data:/app/data 
    environment:
      - filename=example_captured_data.json

  analyzer:
    build: ./ExampleAnalyzer
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - filename=processed.example_captured_data.json