---
version: '3.5'

services:
  api:
    build:
      context: ./API
    command: ["sh", "-c", "/wait && dotnet API.dll"]
    hostname: api
    ports:
      - "4321:80"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
    env_file:
      - .env
      - server.info.env
    networks:
      - ec-network
    healthcheck:
      test: wget --quiet --tries=1 -O /dev/null http://localhost/health/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: mongo:3.6.14
    hostname: db
    ports:
      - "27017:27017"
    volumes:
      - ec-data-volume:/data/db
    networks:
      - ec-network
    healthcheck:
      test: mongo --quiet --eval "db.adminCommand('ping')"
      interval: 1m30s
      timeout: 10s
      retries: 3

  rp:
    image: abiosoft/caddy:1.0.3
    command: ["--conf", "/etc/Caddyfile"]
    hostname: web
    depends_on:
      - api
      - web
    networks:
      - ec-network

  web:
    build:
      context: ./WebUI
    hostname: web
    networks:
      - ec-network

  redoc:
    image: redocly/redoc:v2.0.0-rc.20
    hostname: redoc
    ports:
      - "4322:80"
    depends_on:
      - rp
    environment:
      - SPEC_URL=http://localhost:8090/api/v1/openapi
    networks:
      - ec-network

networks:
  ec-network: {}
