---
version: '3.5'

services:
  api:
    build:
      context: ./API
    command: ["sh", "-c", "/wait && dotnet API.dll"]
    hostname: api
    ports:
      - "4321:80"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
    env_file:
      - .env
    networks:
      - ec-network
    healthcheck:
      test: wget --quiet --tries=1 -O /dev/null http://localhost/health/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: mongo:3.6.14
    hostname: db
    ports:
      - "27017:27017"
    volumes:
      - ec-db-volume:/data/db
    networks:
      - ec-network
    healthcheck:
      test: mongo --quiet --eval "db.adminCommand('ping')"
      interval: 1m30s
      timeout: 10s
      retries: 3

  rp:
    image: abiosoft/caddy:1.0.3
    command: ["--conf", "/etc/Caddyfile"]
    hostname: web
    depends_on:
      - api
      - web
    networks:
      - ec-network

  web:
    build:
      context: ./WebUI
      args:  # Make sure to change the following arg
        REACT_APP_GOOGLE_CLIENT_ID: 555477545658-co1pgbl0uh99rp8tbo2q62t2ch8vlb1h.apps.googleusercontent.com
    hostname: web
    networks:
      - ec-network

  os:
    image: minio/minio:RELEASE.2019-12-30T05-45-39Z
    volumes:
      - ec-os-volume:/data
    ports:
      - "9009:9000"
    hostname: web
    environment:  # Using defaults, do not run in insecure environment
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  ec-network: {}
