#- Name: Jonathan Hirokazu Burns
#- ID: 2288851
#- email: jburns@chapman.edu
#- Course: 353-01
#- Assignment: Submission #2
#- Purpose: Builds, defines and starts the backend

version: '3.7'
services:
  web:
    build: 
      context: ./Receiver
    command: sh -c "/wait && dotnet Receiver.dll"
    ports:
    - "4321:80"
    depends_on:
    - db
    environment:
      WAIT_HOSTS: db:27017
    networks:
     - ec-network
    healthcheck:
       test: wget --quiet --tries=1 -O /dev/null http://localhost/health/ || exit 1
       interval: 1m30s
       timeout: 10s
       retries: 3

  db:
    image: mongo:3.6.14
    hostname: db
    ports:
    - "27017:27017"
    volumes:
    - ec-data-volume:/data/db
    networks:
    - ec-network
    healthcheck:
       test: mongo --quiet --eval "db.adminCommand('ping')"
       interval: 1m30s
       timeout: 10s
       retries: 3

  exporter:
    build: 
      context: ./Exporter
    command: sh -c "/wait && dotnet Exporter.dll"
    depends_on:
      - db
    environment:
      - WAIT_HOSTS=db:27017
    networks:
      - ec-network

##### Legacy beyond here

  analyzer:
    build: ./ExampleAnalyzer
    volumes:
      - ./data:/usr/src/app/data
    environment:
      - filename=processed.example_captured_data.json

volumes:
  ec-data-volume:

networks:
  ec-network:
