version: '3'
services:
  receiver:
    build: ./Receiver
    ports:
    - "4321:80"
    volumes:
      - ./data:/app/data

  processor:
    build: ./processor
    volumes:
      - ./data:/app/data 
    environment:
      - filename=example_captured_data.json