version: '3.5'

services:
  web:
    volumes:
      - ./WebUI/:/app/
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
    - "3003:3000"