version: '3.5'

services:
  web:
    volumes:
      - ./WebUI/:/app/
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
    - "3003:3000"

  rp:
    ports:
    - "8090:2015"
    volumes:
    - ./Caddy/Caddyfile:/etc/Caddyfile

  exporter:
    build: 
      context: ./Exporter
    command: sh -c "/wait && dotnet Exporter.dll"
    depends_on:
      - db
    volumes:
      - ./data/:/app/data
    environment:
      - WAIT_HOSTS=db:27017
    networks:
      - ec-network