---
jobs:
  build:
    name: End-To-End Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker Compose
        run: docker-compose up cy
        working-directory: ./Server

name: Cypress

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'Server/**'
      - '.github/workflows/cypress-integration.yml'
