---
jobs:
  build:
    name: End-To-End Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          context: ./Server/API
          dockerfile: integration.Dockerfile
          image_name: jhburns/ec-receiver-cache
          password: "${{ secrets.DOCKER_PASSWORD }}"
          username: "${{ secrets.DOCKER_USERNAME }}"

name: Cypress

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'Server/**'
      - '.github/workflows/cypress-integration.yml'
