---
jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ./Server
    name: End-To-End Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: cp template.env .env
      - name: Build images (is a separate step to work in parallel)
        run: docker-compose build --parallel
      - name: Run Docker Compose
        run: docker-compose up cy

name: Cypress

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'Server/**'
      - '.github/workflows/cypress-integration.yml'
