---
name: DemoGame

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'DemoGame/**'
      - '.github/workflows/demo-game-integration.yml'

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          context: ./DemoGame
          dockerfile: Dockerfile
          image_name: jhburns/ec-games-cache
          build_extra_args: |
            --build-arg
            username="$username"
            --build-arg
            password="$password"
            --build-arg
            serial="$serial"
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
        env:
          username: ${{ secrets.UNITY_USERNAME }}
          password: ${{ secrets.UNITY_PASSWORD }}
          serial: ${{ secrets.UNITY_SERIAL }}
