---
jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          context: ./
          dockerfile: integration.Dockerfile
          image_name: jhburns/ec-dockerfile-cache
          password: "${{ secrets.DOCKER_PASSWORD }}"
          username: "${{ secrets.DOCKER_USERNAME }}"

name: Dockerfile

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - '**/*Dockerfile*'
      - '*Dockerfile*'
      - '.github/workflows/dockerfile-integration.yml'
      - 'integration.Dockerfile'
