---
jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          context: ./
          dockerfile: docker-compose.integration.Dockerfile
          image_name: jhburns/ec-docker-compose-cache
          password: "${{ secrets.DOCKER_PASSWORD }}"
          username: "${{ secrets.DOCKER_USERNAME }}"

name: Docker Compose

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'Server/**'
      - 'Deploy/**'
      - '.github/workflows/docker-compose-integration.yml'
      - 'docker-compose.integration.Dockerfile'
