---
name: Dockerfile and Yaml

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
      - temp-master
    paths:
      - '**/*Dockerfile*'
      - '**/*.yaml'
      - '**/*.yml'
      - '*Dockerfile*'
      - '*.yaml'
      - '*.yml'
      - '.github/workflows/dockerfile-and-yaml-integration.yml'

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-dockerfile-and-yaml-cache
          context: ./
          dockerfile: Dockerfile.integration
