name: Other Integration

on:
  pull_request:
    branches:    
      - master
    paths-ignore:
    - 'Server/Receiver/**'
    - '.github/workflows/receiver-integration.yml'

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-18.04
    steps:
      - name: Notify
        run: echo "Hello, this only so CI can pass for the rest of paths"

