---
name: Packer

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'Deploy/Packer/**'
      - '.github/workflows/packer-integration.yml'

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-packer-cache
          context: ./Deploy/Packer
          dockerfile: integration.Dockerfile
          build_extra_args:
            "--build-arg CI_PULL_REQUEST=223
            --build-arg CI_REPO_OWNER=jhburns
            --build-arg CI_REPO_NAME=ExperienceCapture
            --build-arg CI_COMMIT=$GITHUB_SHA
            --build-arg REVIEWDOG_TOKEN=${{ secrets.REVIEWDOG_TOKEN }}"
