---
jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_BUILDKIT: 1
        name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          context: ./Deploy/Packer
          dockerfile: integration.Dockerfile
          image_name: jhburns/ec-packer-cache
          password: "${{ secrets.DOCKER_PASSWORD }}"
          username: "${{ secrets.DOCKER_USERNAME }}"

name: Packer

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'Deploy/Packer/**'
      - '.github/workflows/packer-integration.yml'
