name: Receiver Integration

on:
  push:
    paths:
    - 'Server/Receiver/**'
    - '.github/workflows/receiver-integration.yaml'

jobs:
  build:
    # Job name is Greeting
    name: Check Build
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: '../Server/Receiver/action.yaml'
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
