name: Receiver Integration

on:
  push:
    paths:
    - 'Server/Receiver/**'
    - '.github/workflows/receiver-integration.yml'

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-18.04
    steps:
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: whoan/docker-images/node