name: Receiver Integration

on:
  pull_request:
    branches:    
      - master
    paths:
    - 'Server/Receiver/**'
    - '.github/workflows/receiver-integration.yml'

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-18.04
    env:
      Ghabuild: 'True'
    steps:
      - uses: actions/checkout@v1
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-receiver-cache
          context: ./Server/Receiver
      - run: echo "$GHA_BUILD"