---
jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          context: ./
          dockerfile: report.integration.Dockerfile
          image_name: jhburns/ec-report-cache
          password: "${{ secrets.DOCKER_PASSWORD }}"
          username: "${{ secrets.DOCKER_USERNAME }}"

name: Report

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
