---
name: Report

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-report-cache
          context: ./
          dockerfile: report.integration.Dockerfile
    env:
      DOCKER_BUILDKIT: 1
