---
jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - env:
          DOCKER_BUILDKIT: 1  # Needed so that docker build will read in correct .dockerignore
        name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          build_extra_args: |
            --build-arg username=${{ secrets.UNITY_USERNAME }}
            --build-arg password=${{ secrets.UNITY_PASSWORD }}
            --build-arg serial=${{ secrets.UNITY_SERIAL }}
          context: .
          dockerfile: SetupTestGame/Dockerfile
          image_name: jhburns/ec-games-cache
          password: "${{ secrets.DOCKER_PASSWORD }}"
          username: "${{ secrets.DOCKER_USERNAME }}"

name: SetupGame

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - 'SetupTestGame/**'
      # This check is special, its cross-project
      # Changes in the client also should trigger a check
      - 'ClientDevelopmentGame/**'
      - '.github/workflows/dev-game-integration.yml'
