---
name: Shell

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - '**/*.sh'
      - '*.sh'
      - '.github/workflows/shell-integration.yml'
      - 'Dockerfile.shellcheck.integration'

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-shellcheck-cache
          context: ./
          dockerfile: shellcheck.integration.Dockerfile
