---
name: Spellcheck

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - '**/*.md'
      - '*.md'
      - '.github/workflows/spellcheck-integration.yml'
      - 'spelling.integration.Dockerfile'

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v3.1.1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-spellcheck-cache
          context: ./
          dockerfile: spelling.integration.Dockerfile
