---
name: Spellcheck

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
      - temp-master
    paths:
      - '**/*.md'
      - '*.md'
      - '.github/workflows/spellcheck-integration.yml'
      - 'Dockerfile.spelling.integration'

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-spellcheck-cache
          context: ./
          dockerfile: Dockerfile.spelling.integration
