---
name: Yaml

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '*.yaml'
      - '*.yml'
      - '.github/workflows/yaml-integration.yml'
      - 'Dockerfile.yaml.integration'

jobs:
  build:
    name: Integration Checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker
        uses: whoan/docker-build-with-cache-action@v1
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jhburns/ec-yaml-cache
          context: ./
          dockerfile: yaml.integration.Dockerfile
